name: Main
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - run: echo "this is test actions"
     - uses: subosito/flutter-action@v2
       with:
          flutter-version: '3.7.7'
          channel: 'stable'
     - run: flutter --version
